version: '3.8'

services:
  backend:
    build: ../granabox_backend
    container_name: granabox_backend
    ports:
      - "5000:5000"
    volumes:
      - ../granabox_backend:/app
  
  frontend:
    build: .
    container_name: granabox_frontend
    ports:
      - "80:80"
    depends_on:
      - backend